module.exports = {
    name: "makingneon",
    alias: ["neon", "neontext"],
    category: "logo",
    description: "Generate Making Neon Text Logo",

    async execute(sock, msg, args) {
        const jid = msg.key.remoteJid;
        const text = args.join(" ").trim();

        if (!text) {
            return sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Example:\n.neon AKIRA-BOT"
                },
                { quoted: msg }
            );
        }

        const url =
            `https://jerrycoder.oggyapi.workers.dev/ephoto/makingneon?text=${encodeURIComponent(text)}`;

        await sock.sendMessage(
            jid,
            {
                image: { url },
                caption:
`${text}

> *Generated by AKIRA-BOT*`
            },
            { quoted: msg }
        );
    }
};